clc; clear all; close all;

fig = figure('color','white','position',[40 300 600 400]);
hold on;
xlim([0 5]);
ylim([-7 -2]);
set(gca,'ydir','normal');
set(gca,'ytick',-7:0.5:-2);
ylabelString = get(gca,'yticklabel');

% plot(0.02,-1.5,'^','markersize',14,'markerfacecolor','k','markeredgecolor','k');
set(gca,'linewidth',3);
set(gca,'yticklabel',ylabelString);
ylabel('Energy level (eV)');
set(gca,'xtick',[]);
set(gca,'xcolor',[1 1 1]);
set(gca,'fontweight','bold');
set(gca,'fontsize',14);

% - - - - - - - - - -

itransition = 0;

ito_ef = -4.73; % - - - - - - - - - - ITO EF
plot([itransition+0.5 itransition+1], ...
    [ito_ef ito_ef], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    ito_ef+0.25, ...
    num2str(ito_ef, '%.1f'), ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');
text(itransition+0.75, ...
    ito_ef-0.25, 'ITO', ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold', ...
    'Color', [0 191 255]/255);

% - - - - - - - - - -

itransition = 1;

pedot_ea = -3.0; % - - - - - - - - - - PEDOT:PSS EA
plot([itransition+0.5 itransition+1], ...
    [pedot_ea pedot_ea], ...
    'k', ...
    'Linewidth',3);
text(itransition+0.75, ...
    pedot_ea+0.25, ...
    num2str(pedot_ea,'%.1f'), ...
    'horizontalalignment','center', ...
    'fontsize',14, ...
    'fontweight','bold');


pedot_ie = -5.1; % - - - - - - - - - - PEDOT:PSS IE
plot([itransition+0.5 itransition+1], ...
    [pedot_ie pedot_ie], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    pedot_ie-0.25, ...
    num2str(pedot_ie,'%.1f'), ...
    'horizontalalignment','center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');
text(itransition+0.75, ...
    pedot_ie-0.5, ...
    'PEDOT:PSS', ...
    'horizontalalignment','center', ...
    'fontsize', 14, ...
    'fontweight','bold', ...
    'Color', [106 90 205]/255);

pedot_ef = -5.0; % - - - - - - - - - - PEDOT:PSS EF
plot([itransition+0.5 itransition+1], ...
    [pedot_ef pedot_ef], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    pedot_ef+0.25, ...
    num2str(pedot_ef,'%.1f'), ...
    'horizontalalignment','center', ...
    'fontsize', 14, ...
    'fontweight','bold');

% - - - - - - - - - -

itransition = 2;

rp_ea = -3.6; % - - - - - - - - - - RP EA
plot([itransition+0.5 itransition+1], ...
    [rp_ea rp_ea], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    rp_ea+0.25, ...
    num2str(rp_ea, '%.1f'), ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');

rp_ie = -5.5; % - - - - - - - - - - RP IE
plot([itransition+0.5 itransition+1], ...
    [rp_ie rp_ie], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    rp_ie-0.25, ...
    num2str(rp_ie,'%.1f'), ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');
text(itransition+0.75, ...
    rp_ie-0.5, ...
    'RPP [n = 5]', ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold', ...
    'Color', [128 0 128]/255);

% rp_ef = -5.0; % - - - - - - - - - -  RP EF
% plot([itransition+0.5 itransition+1], ...
%     [rp_ef rp_ef], ...
%     'k', ...
%     'Linewidth', 3);
% text(itransition+0.75, ...
%     rp_ef+0.25, ...
%     num2str(rp_ef,'%.1f'), ...
%     'horizontalalignment','center', ...
%     'fontsize', 14, ...
%     'fontweight','bold');

% - - - - - - - - - -

itransition = 3;

pcbm_ea = -3.8;
plot([itransition+0.5 itransition+1], ...
    [pcbm_ea pcbm_ea], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    pcbm_ea+0.25, ...
    num2str(pcbm_ea,'%.1f'), ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');

pcbm_ie = -6.2;
plot([itransition+0.5 itransition+1], ...
    [pcbm_ie pcbm_ie], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    pcbm_ie-0.25, ...
    num2str(pcbm_ie,'%.1f'), ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');
text(itransition+0.75, ...
    pcbm_ie-0.5, ...
    'PCBM', ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold', ...
    'Color', [0 51 102]/255);

pcbm_ef = -3.9;
plot([itransition+0.5 itransition+1], ...
    [pcbm_ef pcbm_ef], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    pcbm_ef-0.25, ...
    num2str(pcbm_ef,'%.1f'), ...
    'horizontalalignment','center', ...
    'fontsize', 14, ...
    'fontweight','bold');

% - - - - - - - - - -

itransition = 4;

ag_ef = -4.26;
plot([itransition+0.5 itransition+1], ...
    [ag_ef ag_ef], ...
    'k', ...
    'Linewidth', 3);
text(itransition+0.75, ...
    ag_ef+0.25, ...
    num2str(ag_ef,'%.1f'), ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold');
text(itransition+0.75, ...
    ag_ef-0.25, ...
    'Ag', ...
    'horizontalalignment', 'center', ...
    'fontsize', 14, ...
    'fontweight', 'bold', ...
    'Color', [192, 192, 192]/255);

hold off;